[package]
name = "findex-translator"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.3"
findex-plugin = "0.8.2"
regex = "1.10.6"
shellexpand = "3.1.0"
